version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:tajneheslo@db:5432/maturita
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tajneheslo
      - POSTGRES_DB=maturita
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: