services:
  web:
    build: .
    ports:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://admin:tajneheslo@db:5432/maturita
      - OPENAI_BASE_URL=https://kurim.ithope.eu/v1
      - OPENAI_API_KEY=sk-0MlocXvcIJNS9usp-OlaAg
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tajneheslo
      - POSTGRES_DB=maturita
      - PGDATA=/data/pgdata
