services:
  web:
    build: .
    ports:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://admin:tajneheslo@db:5432/maturita
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tajneheslo
      - POSTGRES_DB=maturita
      - PGDATA=/data/pgdata
